services:
  auth-db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - auth-db:/var/lib/postgresql/data
    networks: [app-net]

  inventory-db:
    image: postgres:15
    container_name: inventory_db
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: ${INV_DB_USER}
      POSTGRES_PASSWORD: ${INV_DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${INV_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - inventory-db:/var/lib/postgresql/data
    networks: [app-net]

  orders-db:
    image: postgres:15
    container_name: orders_db
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: ${ORD_DB_USER}
      POSTGRES_PASSWORD: ${ORD_DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ORD_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - orders-db:/var/lib/postgresql/data
    networks: [app-net]

  payments-db:
    image: postgres:15
    container_name: payments_db
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: ${PAY_DB_USER}
      POSTGRES_PASSWORD: ${PAY_DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PAY_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - payments-db:/var/lib/postgresql/data
    networks: [app-net]
